config/routes.rb
HomeBudget::Application.routes.draw do
  root :to => "transactions#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  resources :transactions
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role
  include Mongoid::Document
  
  has_and_belongs_to_many :users
  belongs_to :resource, :polymorphic => true
  
  field :name, :type => String
  index({ :name => 1 }, { :unique => true })


  index({
    :name => 1,
    :resource_type => 1,
    :resource_id => 1
  },
  { :unique => true})
  
  scopify
end

app/models/transaction.rb
class Transaction
  include Mongoid::Document
  include Mongoid::Timestamps

  field :id, type: String
  field :name, type: String
  field :value, type: Float, default: 0

  validates_presence_of :name
  # run 'rake db:mongoid:create_indexes' to create indexes

  #belongs_to :user
  embedded_in :user, inverse_of: :transactions

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  rolify
  field :provider, type: String
  field :uid, type: String
  field :name, type: String
  field :email, type: String


  validates_presence_of :name
  # run 'rake db:mongoid:create_indexes' to create indexes

  #has_many :transactions
  embeds_many :transactions


  index({ email: 1 }, { unique: true, background: true })

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end


  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end


  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
# Reset the session after successful login, per
# 2.8 Session Fixation – Countermeasures:
# http://guides.rubyonrails.org/security.html#session-fixation-countermeasures
    reset_session
    session[:user_id] = user.id
    user.add_role :admin if User.count == 1 # make the first user an admin
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url, :notice => 'Signed in!'
    end

  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @transactions = Transaction.all
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end
  
  def show
    @transaction = Transaction.find(params[:id])
  end

  def create
    @transaction = @current_user.transactions.build(transaction_params)
    @transaction.save
    redirect_to transactions_path, :notice => 'Transaction added!'
  end

  def update
    @transaction = @current_user.transactions.find(params[:id])
    if @transaction.update_attributes(transaction_params)
      redirect_to transactions_path
    else
      redirect_to transactions_path
    end
  end

  def destroy
    @current_user.transactions.find(params[:id]).destroy
    redirect_to transactions_path, :notice => 'Transaction deleted!'
  end

private

def transaction_params
  params.require(:transaction).permit(:name, :value)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end


  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.name, user}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.erb
<%= link_to "HomeBudget", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', signout_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', signin_path %>
    </li>
  <% end %>
    <li>
    <%= link_to 'Transactions', transactions_path %>
    </li>
  <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/_navigation.html.haml
= link_to "Homebudget", root_path, :class => 'brand'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Homebudget"
      %meta{:content => content_for?(:description) ? yield(:description) : "Homebudget", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/transactions/_transaction.html.haml
.modal{:id => "role-options-#{transaction.id}", :style => "display: none;"}
  = simple_form_for transaction, :url => transaction_path(transaction), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Edit transaction
    .modal-body
      = f.input :name
      = f.input :value
    .modal-footer
      = f.submit "Edit!", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/transactions/index.html.haml
%h3 Transactions
.transactions
  %table.table.table-condensed
    %thead
      %tr
        %th Date
        %th Name
        %th Value
        %th Edit
        %th Delete
    %tbody
      - @current_user.transactions.each do |transaction|
        - if transaction.value > 0
          -status = 'success'
        - else
          -status = 'error'
        %tr{:class => status}
          %td= transaction.created_at.to_date.to_formatted_s(:short)
          %td= transaction.name
          %td= number_to_currency(transaction.value, :unit => "€", precision: 1) 
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{transaction.id}", :type => "button"} Edit
            = render transaction
          %td= link_to 'Delete', transaction, method: :delete, data: { confirm: 'Are you sure?' }

%br.clearfix
%h4 New Transaction
= form_for [@user, Transaction.new] do |f|
  = f.label :name
  = f.text_field :name
  %br/
  = f.label :value
  = f.text_field :value
  %br/
  = f.submit "Add transaction"

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/edit.html.haml
= form_for(@user) do |f|
  = f.label :email
  = f.text_field :email
  %br/
  = f.submit "Sign in"

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}
%p
  Created at: #{@user.created_at}